# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"NumbaSOM": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://nmarincic.github.io/numbasom/"

git_url = "https://github.com/nmarincic/numbasom/tree/master/"

def custom_doc_links(name): return None
