# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SOM": "00_core.ipynb",
         "normalize": "00_core.ipynb",
         "normalize_with_mutate": "00_core.ipynb",
         "pairwise": "00_core.ipynb",
         "pairwise_squared": "00_core.ipynb",
         "random_lattice": "00_core.ipynb",
         "get_all_BMU_indexes": "00_core.ipynb",
         "som_calc": "00_core.ipynb",
         "adapt": "00_core.ipynb",
         "euclidean": "00_core.ipynb",
         "euclidean_squared": "00_core.ipynb",
         "u_matrix": "00_core.ipynb",
         "project_on_som": "00_core.ipynb",
         "find_closest_data_index": "00_core.ipynb",
         "lattice_closest_vectors": "00_core.ipynb",
         "find_closest": "00_core.ipynb",
         "save_lattice": "00_core.ipynb",
         "load_lattice": "00_core.ipynb",
         "plot_u_matrix": "01_viz.ipynb"}

modules = ["core.py",
           "viz.py"]

doc_url = "https://nmarincic.github.io/numbasom/"

git_url = "https://github.com/nmarincic/numbasom/tree/master/"

def custom_doc_links(name): return None
