# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['NumbaSOM']

# Cell
class NumbaSOM:
    """Instantiates the class with data"""
    def __init__(self, som_size, num_iterations, data, is_torus=False, isScaled=False):
        print ("hello")

    def say_hello(self, to):
        "say hello to somebody"
        return (f'Hello {to}!')