package:
  name: numbasom
  version: 0.0.3
source:
  sha256: b84608e0664bd03bbf1b1e45e6c6f1783385ec3f22de607f7e263adcdb7870d3
  url: https://files.pythonhosted.org/packages/cf/e2/ddfd171593f72816cb569608dac7c916b95256bbdf927aa5d2678dda91bb/numbasom-0.0.3.tar.gz
about:
  dev_url: https://nmarincic.github.io
  doc_url: https://nmarincic.github.io
  home: https://nmarincic.github.io
  license: Apache Software
  license_family: APACHE
  summary: A Fast Self-Organizing Map Python Library Implemented in Numba
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - nmarincic
requirements:
  host:
  - pip
  - python
  - packaging
  - fastcore
  - nbconvert==5.6.1
  - jupyter-client==6.1.2
  - numba
  - numpy
  - matplotlib
  run:
  - pip
  - python
  - packaging
  - fastcore
  - nbconvert==5.6.1
  - jupyter-client==6.1.2
  - numba
  - numpy
  - matplotlib
test:
  imports:
  - numbasom
