package:
  name: numbasom
  version: 0.0.5
source:
  sha256: c3e14bae64e56b3f38f415d31525bd5c7c91e56f8c23ca5bf6531ed3ea21d6eb
  url: https://files.pythonhosted.org/packages/36/ab/794740e7f017888530a38dbc3e5db4a995b6b6dd8fe8536886d051db2c64/numbasom-0.0.5.tar.gz
about:
  dev_url: https://nmarincic.github.io
  doc_url: https://nmarincic.github.io
  home: https://nmarincic.github.io
  license: Apache Software
  license_family: APACHE
  summary: A Fast Self-Organizing Map Python Library Implemented in Numba
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - nmarincic
requirements:
  host:
  - pip
  - python
  - packaging
  - numba
  - numpy
  - matplotlib
  run:
  - pip
  - python
  - packaging
  - numba
  - numpy
  - matplotlib
test:
  imports:
  - numbasom
